openapi: 3.1.0
info:
  title: Galactis.ai API
  version: 0.1.0
servers:
  - url: https://api.galactis.ai
paths:
  /api/v1/agents/create:
    post:
      summary: Create a new AI agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                  enum: [voice, chat, workflow, rpa]
                model:
                  type: string
                integrations:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Agent created successfully

